repos:
  - repo: local
    hooks: 
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--fail-under=8.0"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
