name: Pull Request Check

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Lint test
        run: pylint . --fail-under=8.0
    
      - name: Show data
        run: |
          "Login: ${{ github.event.pull_request.user.login }}"
          "Nome: ${{ github.event.pull_request.user.name }}"